name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # executa a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: xgustavu
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar no GitHub Pages
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
